openapi: 3.0.1
info:
  title: test01
  description: API Definition of test01
  version: 1.0.0
servers:
- url: http://localhost:8290/test01
paths:
  /:
    get:
      responses:
        default:
          description: Default response
